// src/components/DropField.tsx
import { useEffect, useRef } from 'react';

import { getPathForFile, getSelectedResult } from '@/adapters/electron';

import './DropField.scss';

const getFileExtension = (name) => {
  const parts = name.split('.');
  if (parts.length < 2) return '';

  return parts.pop().toLowerCase();
};

const isAllowExt = (type, ext) => {
  return type === 'text/plain' || type === 'application/text' || ext === 'txt' || ext === 'md' || ext === 'mii';
};

export default function DropField({ onOpenFilePath }) {
  const dropZoneRef = useRef(null);

  useEffect(() => {
    const dropZone = dropZoneRef.current;

    const resetOverlay = () => {
      dropZone.style.opacity = null;
      dropZone.style.zIndex = null;
    };
    const onWindowDrop = (event) => {
      event.preventDefault();
      Array.from(event.dataTransfer.files as FileList).forEach((file) => {
        const path = getPathForFile(file);
        const ext = getFileExtension(file.name);

        if (isAllowExt(file.type, ext)) {
          onOpenFilePath(path);
          return;
        }

        getSelectedResult({
          title: 'error',
          type: 'error',
          buttons: ['OK'],
          message: path,
          detail: 'This file format is not supported.',
        });
      });
    };
    const onDragEnter = (event) => {
      if (!event.dataTransfer || !event.dataTransfer.types.includes('Files')) return;
      dropZone.style.opacity = 1;
      dropZone.style.zIndex = 100;
    };
    const onDropZoneDrop = (event) => {
      event.preventDefault();
      resetOverlay();
    };
    const onDocumentDragStart = (event) => {
      if (event.target.closest?.('[draggable="true"]')) return;
      event.preventDefault();
    };
    const onDragOver = (event) => {
      event.preventDefault();
    };

    window.addEventListener('drop', onWindowDrop, true);
    window.addEventListener('dragenter', onDragEnter);
    dropZone.addEventListener('dragleave', resetOverlay);
    dropZone.addEventListener('drop', onDropZoneDrop);
    document.addEventListener('dragstart', onDocumentDragStart);
    window.addEventListener('dragover', onDragOver);

    return () => {
      window.removeEventListener('drop', onWindowDrop, true);
      window.removeEventListener('dragenter', onDragEnter);
      dropZone.removeEventListener('dragleave', resetOverlay);
      dropZone.removeEventListener('drop', onDropZoneDrop);
      document.removeEventListener('dragstart', onDocumentDragStart);
      window.removeEventListener('dragover', onDragOver);
    };
  }, [onOpenFilePath]);

  return <div ref={dropZoneRef} className="dropfield" />;
}

// src/renderer/components/DropField.vue
<template>
  <div>
    <div class="dropzone"/>
  </div>
</template>

<script>
import { getSelectedResult } from '@/modules/dialog.js';

export default {
  name: 'DropField',
  mounted: function() {
    this.init();
  },
  methods: {
    init: function() {
      this.dropOverlay();

      window.addEventListener(
        'drop',
        e => {
          e.preventDefault();
          let file = e.dataTransfer.files[0];
          let ext = file.name.split('.')[1];
          if (process.env.NODE_ENV === 'development') console.log(file);
          this.dropFile(file, ext);
        },
        true,
      );
    },
    dropFile(file, ext) {
      if (
        file.type === 'text/plain' ||
        file.type === 'application/text' ||
        ext === 'txt' ||
        ext === 'md' ||
        ext === 'mii'
      ) {
        this.$parent.readFile(file.path);
      } else {
        getSelectedResult({
          title: 'error',
          type: 'error',
          buttons: ['OK'],
          detail: 'This file format is not supported.',
        });
      }
    },
    dropOverlay: function() {
      let dropZone = document.querySelector('.dropzone');

      window.addEventListener('dragenter', function(e) {
        dropZone.style.opacity = 1;
        dropZone.style.zIndex = 100;
      });

      dropZone.addEventListener('dragleave', function(e) {
        this.style.opacity = null;
        this.style.zIndex = null;
      });

      dropZone.addEventListener('drop', function(e) {
        e.preventDefault();
        this.style.opacity = null;
        this.style.zIndex = null;
      });

      document.addEventListener('dragstart', function(e) {
        e.preventDefault();
      });

      window.addEventListener('dragover', function(e) {
        e.preventDefault();
      });
    },
  },
};
</script>

<style scoped>
</style>
